[package]
name = "password_store"
version = "0.1.0"
authors = ["Gustavo Aguiar <gugahoa@gmail.com>"]

[lib]
name = "op"
path = "src/lib/lib.rs"

[dependencies]
thunder = "0.3.1"
clap = "2.31.2"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
